name: module3_task0

on:
  schedule:
  - cron: "0 0 0 * * ?"
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: validate that the Makefile is present
      run: make help
