name: module3_task1

on:
  schedule:
    - cron: "0 0 * * *"
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install required tools
        uses: ./setup.sh

      - name: validate that the Makefile is present
        run: make build -C module3_task0
