---
name: module3_task0

on:
  schedule:
  - cron: "0 0 0 * *-5"
  [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v3

    - name: validate that the Makefile is present
      run: make help -C module3_task0
...