---
name: module3_task2

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install required tools
        run: cd module3_task1 && sudo ./setup.sh

      - name: lint
        run: markdownlint README.md DEPLOY.md

      - name: Unit test
        run: sudo make unit-tests -C module3_task2

      - name: test2
        run: sudo make integration-tests -C module3_task1

      - name: help
        run: sudo make help -C module3_task2

      - name: Build command
        run: sudo make build -C module3_task2

      - name: package
        run: sudo make package -C module3_task2
...
