name: module3_task1

on:
  schedule:
    - cron: "0 0 * * *"
  push:
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install required tools
        run: cd module3_task1 && sudo ./setup.sh

      - name: Build command
        run: make build -C module3_task1
