---
name: module4_task2

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - "main"
    tags:
      - "v*.*.*"
  pull_request:
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install required tools
        run: cd module4_task2 && sudo ./setup.sh

      - name: lint
        run: make lint -C module4_task2 && echo OK || echo FAILED

      - name: help
        run: make help -C module4_task2

      - name: Build command
        run: make build -C module4_task2

      - name: package
        run: make package -C module4_task2

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            module4_task2/DEPLOY.md
            module4_task2/awesome-website.zip

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: './module4_task2/dist'
          production-branch: main
          github-token: ${{ secrets.REPO_TOKEN }}
          deploy-message: "🎉 Published on"
          enable-pull-request-comment: true
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1

      - name: docker-build
        run: make build-docker -C module4_task2

      - name: make-tests
        run: |
          docker run -i "awesome:build" make -C module4_task2 clean build unit-tests integration-tests

      - name: docker-tests
        run: make docker-tests -C module4_task2 && echo OK || echo FAILED
...
